# -*- coding: utf-8 -*-
"""R note_taker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0PYNj86BbrV1-vLm3j6n-fq_npibF4l
"""

import os

class NoteTaker:

  """

    This Class has the function of making data notes or analysis notes

  """

  def __init__(self):

    self.annotation:dict = {}

  def write_line(self, topic, value):
      
    """
    
        This method store one data or analysis in the class

        Args:
            topic (str): name of data/analysis
            value (str): value of fata/analysis
    
    """
    print(f"{topic}: {value}")
    self.annotation[topic] = value

  def save(self, saved_file_name, directory):

    """
      This method save the annotation in txt file

      Args:
        saved_file_name (str): saved file name
        directory (str): directory to save the file

    """

    with open(os.path.join(directory, saved_file_name),"w") as file:

      for key, value in self.annotation.items():
        file.write(f'{key}: {value}\n')
